version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    # para reiniciar o container quando a máquina for ligada
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASS=123456
